language: python

python:
  - "2.7"

sudo: true
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

install:
  - git clone --depth=1 https://github.com/oca/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

before_install:
  - sudo apt-get install swig

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
